/*
 * lesson5/c_c++/homework/homework5_10.cpp
 */

#include <iostream>

void numberInWords(int numb_n) {
    switch (numb_n) {
    case 1: std::cout << "один!\n";
	break;
    case 2: std::cout << "два!\n";
	break;
    case 3: std::cout << "три!\n";
	break;
    case 4: std::cout << "четыре!\n";
	break;
    case 5: std::cout << "пять!\n";
	break;
    case 6: std::cout << "шесть!\n";
	break;
    case 7: std::cout << "семь!\n";
	break;
    case 8: std::cout << "восемь!\n";
	break;
    case 9: std::cout << "девять!\n";
	break;
    case 10: std::cout << "десять!\n";
	break;
    case 11: std::cout << "одиннадцать!\n";
	break;
    case 12: std::cout << "двенадцать!\n";
	break;
    case 13: std::cout << "тринадцать!\n";
	break;
    case 14: std::cout << "четырнадцать!\n";
	break;
    case 15: std::cout << "пятнадцать!\n";
	break;
    case 16: std::cout << "шестнадцать!\n";
	break;
    case 17: std::cout << "семнадцать!\n";
	break;
    case 18: std::cout << "восемнадцать!\n";
	break;
    case 19: std::cout << "девятнадцать!\n";
	break;
    case 20: std::cout << "двадцать!\n";
	break;
    case 21: std::cout << "двадцать один!\n";
	break;
    case 22: std::cout << "двадцать два!\n";
	break;
    case 23: std::cout << "двадцать три!\n";
	break;
    case 24: std::cout << "двадцать четыре!\n";
	break;
    case 25: std::cout << "двадцать пять!\n";
	break;
    case 26: std::cout << "двадцать шесть!\n";
	break;
    case 27: std::cout << "двадцать семь!\n";
	break;
    case 28: std::cout << "двадцать восемь!\n";
	break;
    case 29: std::cout << "двадцать девять!\n";
	break;
    case 30: std::cout << "тридцать!\n";
	break;
    case 31: std::cout << "тридцать один!\n";
	break;
    case 32: std::cout << "тридцать два!\n";
	break;
    case 33: std::cout << "тридцать три!\n";
	break;
    case 34: std::cout << "тридцать четыре!\n";
	break;
    case 35: std::cout << "тридцать пять!\n";
	break;
    case 36: std::cout << "тридцать шесть!\n";
	break;
    case 37: std::cout << "тридцать семь!\n";
	break;
    case 38: std::cout << "тридцать восемь!\n";
	break;
    case 39: std::cout << "тридцать девять!\n";
	break;
    case 40: std::cout << "сорок!\n";
	break;
    case 41: std::cout << "сорок один!\n";
	break;
    case 42: std::cout << "сорок два!\n";
	break;
    case 43: std::cout << "сорок три!\n";
	break;
    case 44: std::cout << "сорок четыре!\n";
	break;
    case 45: std::cout << "сорок пять!\n";
	break;
    case 46: std::cout << "сорок шесть!\n";
	break;
    case 47: std::cout << "сорок семь!\n";
	break;
    case 48: std::cout << "сорок восемь!\n";
	break;
    case 49: std::cout << "сорок девять!\n";
	break;
    case 50: std::cout << "пятьдесят!\n";
	break;
    case 51: std::cout << "пятьдесят один!\n";
	break;
    case 52: std::cout << "пятьдесят два!\n";
	break;
    case 53: std::cout << "пятьдесят три!\n";
	break;
    case 54: std::cout << "пятьдесят четыре!\n";
	break;
    case 55: std::cout << "пятьдесят пять!\n";
	break;
    case 56: std::cout << "пятьдесят шесть!\n";
	break;
    case 57: std::cout << "пятьдесят семь!/n";
	break;
    case 58: std::cout << "пятьдесят восемь!\n";
	break;
    case 59: std::cout << "пятьдесят девять!\n";
	break;
    case 60: std::cout << "шестьдесят!\n";
	break;
    case 61: std::cout << "шестьдесят один!\n";
	break;
    case 62: std::cout << "шестьдесят два!\n";
	break;
    case 63: std::cout << "шестьдесят три!\n";
	break;
    case 64: std::cout << "шестьдесят четыре!\n";
	break;
    case 65: std::cout << "шестьдесят пять!\n";
	break;
    case 66: std::cout << "шестьдесят шесть!\n";
	break;
    case 67: std::cout << "шестьдесят семь!/n";
	break;
    case 68: std::cout << "шестьдесят восемь!\n";
	break;
    case 69: std::cout << "шестьдесят девять!\n";
	break;
    case 70: std::cout << "семьдесят!\n";
	break;
    case 71: std::cout << "семьдесят один!\n";
	break;
    case 72: std::cout << "семьдесят два!\n";
	break;
    case 73: std::cout << "семьдесят три!\n";
	break;
    case 74: std::cout << "семьдесят четыре!\n";
	break;
    case 75: std::cout << "семьдесят пять!\n";
	break;
    case 76: std::cout << "семьдесят шесть!\n";
	break;
    case 77: std::cout << "семьдесят семь!\n";
	break;
    case 78: std::cout << "семьдесят восемь!\n";
	break;
    case 79: std::cout << "семьдесят десять\n";
	break;
    case 80: std::cout << "восемьдесят!\n";
	break;
    case 81: std::cout << "восемьдесят один!\n";
	break;
    case 82: std::cout << "восемьдесят два!\n";
	break;
    case 83: std::cout << "восемьдесят три!\n";
	break;
    case 84: std::cout << "восемьдесят четыре!\n";
	break;
    case 85: std::cout << "восемьдесят пять!\n";
	break;
    case 86: std::cout << "восемьдесят шесть!\n";
	break;
    case 87: std::cout << "восемьдесят семь!\n";
	break;
    case 88: std::cout << "восемьдесят восемь!\n";
	break;
    case 89: std::cout << "восемьдесят десять!\n";
	break;
    case 90: std::cout << "девяносто!\n";
	break;
    case 91: std::cout << "девяносто один!\n";
	break;
    case 92: std::cout << "девяносто два!\n";
	break;
    case 93: std::cout << "девяносто три!\n";
	break;
    case 94: std::cout << "девяносто четыре!\n";
	break;
    case 95: std::cout << "девяносто пять!\n";
	break;
    case 96: std::cout << "девяносто шесть!\n";
	break;
    case 97: std::cout << "девяносто семь!\n";
	break;
    case 98: std::cout << "девяносто восемь!\n";
	break;
    case 99: std::cout << "девяносто девять!\n";
	break;
    case 100: std::cout << "сто!\n";
	break;
    case 101: std::cout << "сто один!\n";
	break;
    default: std::cout << "no such number!\n";
    }
}

int main() {
    int numb_i;
    std::cout << "Введите число -> ";
    std::cin >> numb_i;
    numberInWords(numb_i);
    return 0;
}
